### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by oziphantom** [Hammarberg/pixcen#34]
Hi did you see my pull request? To many issues with it, too hacky? Need something tidied? Not interested?

**Comment by Hammarberg** [comment]
Sorry! Just haven't allocated time for Pixcen in the last few months. The code looks clean, just haven't tried it out. Sorry for my inactivity.

**Comment by Hammarberg** [comment]
Merged! Resized the dialog to match the style. Some people will love this feature ;-)
